### ISSUE TITLE
[Lv.4] 질문 및 코드 리뷰 요청 - 신희제

### ISSUE THREAD

**Issue by Shinheeje** [hansololiviakim/whatTheSnack#13]
❓ Review
이번 과제에서 중점을 둔 사항

질의사항
1.  랜더링을 신경안쓰는게 너무 많은거 같아서 useCallBack 처음 사용해봤는데 이렇게 사용하는게 맞나요?

감사합니다.

**Comment by WooMinGy** [comment]
네 그렇게 사용하는게 맞습니다. 
레벨 3 코드에서 이슈가 존재하지 않아 리뷰를 못 남겼습니다. 
그리고 또한 질문들도 더 자세하게 남겨주시면 좋을 것 같아요!
그러면 저도 더 자세하게 남겨드릴 수 있는데 살짝 아쉽습니다.
